server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3305/zeroorder?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


feign:
  okhttp:
    enabled: true