server:
  port: 8081

spring:
  datasource:
#    url: jdbc:mysql://localhost:3305/zeroorder?useSSL=false,useUnicode=true&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


feign:
  okhttp:
    enabled: true